version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 25565:25565
      - 28016:28016
    environment:
      SERVER_NAME: "Dockerized-Minecraft-Server"
      MOTD: "Forge Minecraft Server"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19"
      MODE: "survival"
      MEMORY: "2G"
      LEVEL_TYPE: "DEFAULT"
      ENABLE_RCON: "true"
      RCON_PASSWORD: password
      RCON_PORT: 28016
      SERVER_PORT: 25565
      ENABLE_WHITELIST: "false"
      OPS: "alistarle"
      MAX_PLAYERS: 20
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      PVP: "true"
      LEVEL: "cold"
      TZ: "Europe/Paris"
      GUI: "FALSE"
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  minecraft-exporter:
    image: joshi425/minecraft_exporter
    container_name: minecraft-exporter
    depends_on:
      - minecraft-server
    ports:
      - 8000:8000
    environment:
      RCON_PASSWORD: password
      RCON_PORT: 28016
      RCON_HOST: "minecraft-server"
      FORGE_SERVER: "True"
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ./data/cold:/world
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: unless-stopped
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
  discord_webhook:
    image: benjojo/alertmanager-discord
    container_name: discord_webhook
    ports:
      - "9094:9094"
    restart: unless-stopped
    environment:
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/991802127657746532/yrcqIDFksDac3yFBxlGK11bo-qHJSzc0CxezWlHqV-x84Imew1Iwa-G35rdOYfs7CWqZ"
volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
