{
 "title": "Minecraft Player stats",
 "description": "Player stats Dashboard for Minecraft",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(blocks_mined,player)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks mined",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(blocks_mined{player=\"$player\"}) by (block)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Items crafted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(blocks_crafted{player=\"$player\"}) by (block) != 0",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Blocks collected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(blocks_picked_up{player=\"$player\"}) by (block)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(player_deaths{player=\"$player\"})"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "player_jumps{player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Meters travelled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "cm_traveled{player=\"$player\"} / 1000",
     "legendFormat": "{{  method }}"
    }
   ]
  },
  {
   "title": "Mobs killed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "entities_killed{player=\"$player\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  }
 ]
}